# Generated by Django 2.2.7 on 2019-12-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automovil',
            options={'verbose_name': 'Automovil', 'verbose_name_plural': 'Automoviles'},
        ),
        migrations.AddField(
            model_name='automovil',
            name='imagen',
            field=models.ImageField(null=True, upload_to='automoviles'),
        ),
        migrations.AlterField(
            model_name='automovil',
            name='anio',
            field=models.IntegerField(verbose_name='Año'),
        ),
    ]
